<?php
return [
    // config key as key_code on permission table
    'access'=>[
        'create-category'=>'category_create',
        'read-category'=>'category_read',
        'update-category'=>'category_update',
        'delete-category'=>'category_delete',
        'create-menu'=>'menu_create',
        'read-menu'=>'menu_read',
        'update-menu'=>'menu_update',
        'delete-menu'=>'menu_delete',
        'create-slider'=>'slider_create',
        'read-slider'=>'slider_read',
        'update-slider'=>'slider_update',
        'delete-slider'=>'slider_delete',
        'create-setting'=>'setting_create',
        'read-setting'=>'setting_read',
        'update-setting'=>'setting_update',
        'delete-setting'=>'setting_delete',
        'create-product'=>'product_create',
        'read-product'=>'product_read',
        'update-product'=>'product_update',
        'delete-product'=>'product_delete',
        'create-user'=>'user_create',
        'read-user'=>'user_read',
        'update-user'=>'user_update',
        'delete-user'=>'user_delete',
        'create-role'=>'role_create',
        'read-role'=>'role_read',
        'update-role'=>'role_update',
        'delete-role'=>'role_delete',
    ],
    'table_module'=>[
            'category',
            'menu',
            'slider',
            'product',
            'setting',
            'user',
            'role',
            'test',
        ],
        'module_children'=>[
            'create',
            'read',
            'update',
            'delete'
        ]
]
 ?>
